### ISSUE TITLE
Compiler error when using discrimated union

### ISSUE THREAD

**Issue by rookboom** [intellifactory/websharper#444]
I have a simple DU type that I am using in a client server app:

```fsharp
type Response =
| Success
| Error of string
```
    
On the client side, this compiles:

```fsharp
let handle = function
    | Server.Success ->  output.Text <- "Success!"
    | _ -> output.Text <- "Error:" 
handle response
```
This does not:  
```fsharp
let handle = function
    | Server.Success ->  output.Text <- "Success!"
    | Server.Error(msg) -> output.Text <- "Error:" 
handle response
```

                        
Is this supported?      
Here is the error:
```
System.Exception: Error starting website:
System.Reflection.TargetInvocationException: Exception has been thrown by the ta
rget of an invocation. ---> System.Exception: Main: error: Failed to translate p
roperty access: Item.
   at WebSharper.Compilation.compiler@98.Invoke(String message)
   at WebSharper.Compiler.Logger.Log(Message message)
   at WebSharper.Compiler.Translator.error@138-1(Logger logger, Location here, S
tring msg)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList
`1 cons, FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mappin
g, FSharpList`1 x)
   at WebSharper.Compiler.Translator.tCall@151(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Expression q, MethodKind methodKind, FSharpList`1 args)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList
`1 cons, FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mappin
g, FSharpList`1 x)
   at WebSharper.Compiler.Translator.tCall@151(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Expression q, MethodKind methodKind, FSharpList`1 args)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mappin
g, FSharpList`1 x)
   at WebSharper.Compiler.Translator.tCall@151(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Expression q, MethodKind methodKind, FSharpList`1 args)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList
`1 cons, FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mappin
g, FSharpList`1 x)
   at WebSharper.Compiler.Translator.tCall@151(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Expression q, MethodKind methodKind, FSharpList`1 args)
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList
`1 cons, FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mappin
g, FSharpList`1 x)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mappin
g, FSharpList`1 x)
   at WebSharper.Compiler.Translator.tCall@151(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Expression q, MethodKind methodKind, FSharpList`1 args)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mappin
g, FSharpList`1 x)
   at WebSharper.Compiler.Translator.tCall@151(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Expression q, MethodKind methodKind, FSharpList`1 args)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Translator.tExpr@197(Logger logger, Pool iP, Pool mP,
FSharpList`1 remotingProvider, T meta, Location here, FSharpFunc`2 op_BangHat, F
SharpOption`1 exn, Boolean allowMacro, Expression quotation)
   at WebSharper.Compiler.Assembler.visitMethod@65-5.Invoke(Method m)
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList
`1 x)
   at WebSharper.Compiler.Assembler.visitType@101-8.Invoke(Type t)
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList
`1 x)
   at WebSharper.Compiler.Assembler.visitType@101-8.Invoke(Type t)
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList
`1 x)
   at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FS
harpList`1 list)
   at WebSharper.Compiler.FrontEnd.Compiler.CompileAssembly(AssemblyDefinition a
ssembly, Boolean sourceMap)
   at WebSharper.Compiler.FrontEnd.Compiler.Compile(FSharpExpr quotation, Assemb
ly context, FSharpOption`1 name)
   at WebSharper.Compilation.compile(Assembly asm)
   at WebSharper.Owin.WarpMiddleware`1..ctor(Func`2 next, Sitelet`1 sitelet, War
pOptions`1 options)
   at WebSharper.Owin.UseWarp@188.Invoke(Func`2 arg)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Microsoft.Owin.Builder.AppBuilder.BuildInternal(Type signature)
   at Microsoft.Owin.Builder.AppBuilder.Build(Type returnType)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuild
er builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext conte
xt)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider service
s, StartOptions options, Action`1 startup)
   at WebSharper.Warp.Run[EndPoint](Sitelet`1 sitelet, FSharpOption`1 debug, FSh
arpOption`1 url, FSharpOption`1 rootDir, FSharpOption`1 scripted, FSharpOption`1
 assembly)
   at <StartupCode$WebSharper-Warp>.$Warp.Run@222-1.Invoke(String message)
   at WebSharper.Warp.Run[EndPoint](Sitelet`1 sitelet, FSharpOption`1 debug, FSh
arpOption`1 url, FSharpOption`1 rootDir, FSharpOption`1 scripted, FSharpOption`1
 assembly)
   at WebSharper.Warp.RunAndWaitForInput[EndPoint](Sitelet`1 app, FSharpOption`1
 debug, FSharpOption`1 url, FSharpOption`1 rootDir, FSharpOption`1 scripted, FSh
arpOption`1 assembly)
```

**Comment by granicz** [comment]
Indeed, this below gives an error - likely a Warp issue:

```fsharp
open WebSharper

type Result =
    | Success
    | Failure of string

module Server =
    [<Rpc>]
    let Compute () =
        async.Return Success

[<JavaScript>]
module Client =
    open WebSharper.Html.Client

    let Main () =
        let output = P [Text ""]
        Div [
            Button [Text "Click me"]
            |>! OnClick (fun e args ->
                async {
                    let! res = Server.Compute ()
                    match res with
                    | Result.Success ->
                        output.Text <- "Success"
                    | Result.Failure msg ->
                        output.Text <- "Failed: "
                }
                |> Async.Start
            )
            output
        ]

open WebSharper.Html.Server

let MySite =
    Warp.CreateSPA (fun ctx ->
        [Div [ClientSide <@ Client.Main() @>]]
    )

Warp.RunAndWaitForInput(MySite) |> ignore
```

**Comment by Jand42** [comment]
Union field gets were not properly recognized by typed F# quotation to WS quotation transformer (used by Warp). Fixed in commit 11df1b
