### ISSUE TITLE
Error in InlineControl

### ISSUE THREAD

**Issue by deneuxj** [intellifactory/websharper#492]
The example at http://websharper.com/blog-entry/4556/announcing-websharper-suave does not seem to work. I get the following output in my browser when connecting to the application:

```
System.Exception: Error in InlineControl at C:\Users\hudson.IFBUDS02\Server\var\jobs\websharper.ui.next\workspace\WebSharper.UI.Next\Doc.fs: 459.58-459.79: Couldn't find address for method at .$Control.WebSharper-IRequiresResources-Encode@144.Invoke(String message)
at WebSharper.Web.InlineControl`1.WebSharper-IRequiresResources-Encode(Info meta, Provider json)
at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons)
at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list) at WebSharper.Sitelets.Content.metaJson[T](Info m, Provider jP, IEnumerable`1 controls)
at WebSharper.Sitelets.Content.writeResources[a](Env env, IEnumerable`1 controls, FSharpFunc`2 tw) at WebSharper.Sitelets.Content.renderHead@159.Invoke(HtmlTextWriter tw)
at .$Page.get_Default@43.Invoke(FSharpOption`1 doctype, FSharpOption`1 title, FSharpFunc`2 writeHead, FSharpFunc`2 writeBody, HtmlTextWriter writer)
at WebSharper.Sitelets.Content.writeBody@157.Invoke(Stream stream)
at WebSharper.Owin.Internal.W2O.WriteResponse@164.Invoke(Task`1 obj)
```

Versions of dependencies I'm using:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="FSharp.Core" version="3.1.2.5" targetFramework="net452" />
  <package id="IntelliFactory.Reactive" version="3.5.6.61" targetFramework="net452" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net452" />
  <package id="Mono.Cecil" version="0.9.6.1" targetFramework="net452" />
  <package id="Owin" version="1.0" targetFramework="net452" />
  <package id="Suave" version="0.33.0" targetFramework="net452" />
  <package id="WebSharper" version="3.5.15.217" targetFramework="net452" />
  <package id="WebSharper.Charting" version="3.5.9.28" targetFramework="net452" />
  <package id="WebSharper.ChartJs" version="3.5.7.53" targetFramework="net452" />
  <package id="WebSharper.Owin" version="3.5.6.113" targetFramework="net452" />
  <package id="WebSharper.Suave" version="3.5.7.20" targetFramework="net452" />
  <package id="WebSharper.UI.Next" version="3.5.20.194" targetFramework="net452" />
</packages>
```

Compiled with Visual Studio 2015. I'm not sure about this reference to FSharp.Core version 3.1.2.5. I'm compiling with F# 4.0, could there be a compatibility issue? I was having the same problem with Visual Studio 2013, so I don't think that's the problem.

**Comment by deneuxj** [comment]
Here is a simpler example which also fails:

```fsharp

module Main

open WebSharper
open WebSharper.UI.Next.Html
open WebSharper.UI.Next.Server

[<JavaScript>]
let Simple() =
    div []

let MySimplePage =
    Application.SinglePage(fun ctx ->
        Content.Page(
            Title = "Simple",
            Body = [
                div [ client <@ Simple() @> ]
            ]
        )
    )

let MySite =
    Application.SinglePage (fun ctx ->
        Content.Page(
            Body = [
                div [client <@ Simple() @>]
            ])
    )

open Suave.Web
open WebSharper.Suave

let config =
    { defaultConfig with
        logger = Suave.Logging.Loggers.ConsoleWindowLogger(Suave.Logging.LogLevel.Verbose)
    }
startWebServer config (WebSharperAdapter.ToWebPart MySite)
```

**Comment by Tarmil** [comment]
It seems the WebSharper compilation wasn't run. Did you create the project using the Visual Studio template, or simply by pasting the code and adding references to an F# executable project? If the latter, then you need to add the following property into your .fsproj file:

```xml
<PropertyGroup>
  <WebSharperProject>Site</WebSharperProject>
</PropertyGroup>
```

This instructs WebSharper to compile the code to JavaScript and extract the relevant files to `Scripts/` and `Content/`. See the bottom of [this page](http://websharper.com/docs/templates) for more explanations.

**Comment by deneuxj** [comment]
Thanks, that solved it.
