### ISSUE TITLE
AllReferencedAssemblies throws when there is more than one Assembly with the same name

### ISSUE THREAD

**Issue by amieres** [intellifactory/websharper#666]
When two assemblies that are loaded have the same name, for instance:
```
Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a;
Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a;
```

produces an Exception in line 127 of Resources.fs:

```
...
    let asms =
        System.AppDomain.CurrentDomain.GetAssemblies()
        |> Array.filter (fun asm -> not asm.IsDynamic)
    asms |> Array.iter (fun asm -> d.Add(asm.GetName().Name, asm))
...
```

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at WebSharper.Core.Resources.AllReferencedAssemblies@101.Invoke(Unit unitVar)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at WebSharper.Core.Resources.Rendering.TryGetCdn(Context ctx, String assemblyName, String filename)
   at WebSharper.Core.DependencyGraph.AssemblyResource.WebSharper-Core-Resources-IResource-Render(Context ctx)
   at FSI_0006.it@224.Invoke(IResource r) in d:\Abe\CIPHERWorkspace\TestZafirCompiler\TestZafirCompiler\Script.fsx:line 224
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at <StartupCode$FSI_0006>.$FSI_0006.main@() in d:\Abe\CIPHERWorkspace\TestZafirCompiler\TestZafirCompiler\Script.fsx:line 224
Stopped due to error
```

**Comment by Jand42** [comment]
Thanks for the report!

Fix will contain:
* do not throw exception of multiple versions loaded of a non-WebSharper assembly
* throw error with custom message when multiple different versions of a WebSharper assembly are loaded (no way to disambiguate correct metadata)
