### ISSUE TITLE
Exception while building SPA tests project

### ISSUE THREAD

**Issue by Tarmil** [intellifactory/websharper#848]
```
FSC : WebSharper error : Assembly needed for bundling but is not referenced: WebSharper.SPA.Tests [c:\path\to\websharper\tests\WebSharper.SPA.Tests\WebSharper.SPA.Tests.fsproj]
         
         Unhandled Exception: System.NotSupportedException: Exception of type 'System.NotSupportedException' was thrown.
            at Microsoft.FSharp.Core.ExtraTopLevelOperators.dictValueType@98.System-Collections-Generic-IDictionary`2-Add(TKey key, T value)
            at WebSharper.Compiler.CompilationHelpers.trimMetadata(Info meta, IEnumerable`1 nodes) in c:\path\to\websharper\src\compiler\WebSharper.Compiler\CompilationHelpers.fs:line 895
            at <StartupCode$WebSharper-Compiler>.$Bundle.clo@85-85.Invoke(Unit unitVar0) in c:\path\to\websharper\src\compiler\WebSharper.Compiler\bundling\Bundle.fs:line 129
            at WebSharper.Compiler.AssemblyResolver.Wrap[T](FSharpFunc`2 action) in c:\path\to\websharper\src\compiler\WebSharper.Compiler\AssemblyResolution.fs:line 147
            at WebSharper.Compiler.Bundle.render(BundleMode mode, StringWriter writer) in c:\path\to\websharper\src\compiler\WebSharper.Compiler\bundling\Bundle.fs:line 85
            at <StartupCode$WebSharper-Compiler>.$Bundle.t@177-2.Invoke(Unit unitVar) in c:\path\to\websharper\src\compiler\WebSharper.Compiler\bundling\Bundle.fs:line 182
            at System.Lazy`1.CreateValue()
            at System.Lazy`1.LazyInitValue()
            at WebSharper.Compiler.Content.WriteFile(String name, FSharpOption`1 encoding) in c:\path\to\websharper\src\compiler\WebSharper.Compiler\api\Content.fs:line 38
            at WebSharper.Compiler.BundleCommand.write@93.Invoke(Content c, String ext) in c:\path\to\websharper\src\compiler\WebSharper.Compiler\commands\BundleCommand.fs:line 93
            at WebSharper.Compiler.BundleCommand.Exec[a](a env, Config config) in c:\path\to\websharper\src\compiler\WebSharper.Compiler\commands\BundleCommand.fs:line 104
            at WebSharper.Compiler.BundleCommand.Instance@124-1.Invoke(Environment env, Config config) in c:\path\to\websharper\src\compiler\WebSharper.Compiler\commands\BundleCommand.fs:line 124
            at WebSharper.Compiler.Commands.DefineCommand@51.WebSharper-Compiler-Commands-ICommand`1-Execute(Environment env, T cfg) in c:\path\to\websharper\src\compiler\WebSharper.Compiler\commands\Commands.fs:line 53
            at WebSharper.Compile.CommandTools.ExecuteCommands.Bundle(WsConfig settings) in c:\path\to\websharper\src\compiler\WebSharper.Compiler\CommandTools.fs:line 136
            at WebSharper.FSharp.Program.Compile(WsConfig config, WarnSettings warnSettings) in c:\path\to\websharper\src\compiler\WebSharper.FSharp\Program.fs:line 186
            at WebSharper.FSharp.Program.compileMain(String[] argv) in c:\path\to\websharper\src\compiler\WebSharper.FSharp\Program.fs:line 333
            at WebSharper.FSharp.Program.main(String[] argv) in c:\path\to\websharper\src\compiler\WebSharper.FSharp\Program.fs:line 346
```

**Comment by Jand42** [comment]
Overrides are now stored in metadata in the Implementations dictionary, so that they can be looked up by the abstract method signature, but proper signature can be generated for them for TypeScript (it can differ by generic substitution, for example if an abstract method has signature `'T -> 'T` and a subclass inherits `Base<int>`, then the override has signature `int -> int`).

Default implementations do not need this substitution, so they can be in the Methods dictionary, restoring this and making it consistent with the use of Graph nodes.
